#!/usr/bin/env bash

if [ ! -f install ];then
    echo 'install must be run within its container folder' 1>&2
    exit 1
fi

WORKDIR=`pwd`
export GOPATH=$WORKDIR

gofmt -w src

go install test

echo 'finished'

